# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attracker_app', '0006_auto_20150811_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appalachiantrail',
            name='miles',
            field=models.FloatField(default=2189.2, verbose_name='Total number of miles in AT'),
        ),
    ]
